global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'pvz-platform'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kong API Gateway
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: '/metrics'

  # Catalog Service
  - job_name: 'catalog-service'
    static_configs:
      - targets: ['catalog-service:3000']
    metrics_path: '/metrics'

  # Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8081']
    metrics_path: '/actuator/prometheus'

  # Payment Service
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3002']
    metrics_path: '/metrics'

  # Logistics Service
  - job_name: 'logistics-service'
    static_configs:
      - targets: ['logistics-service:8082']
    metrics_path: '/metrics'

  # Config Service
  - job_name: 'config-service'
    static_configs:
      - targets: ['config-service:4000']
    metrics_path: '/metrics'

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Kafka Exporter
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # Node Exporter (System metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
